/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "esm",
  serverDependenciesToBundle: [
    /^three.*/,
    /^@react-three.*/,
    /^@react-three\/drei.*/,
    /^@react-three\/fiber.*/,
    /^@react-three\/postprocessing.*/,
    /^@react-three\/shader.*/,
    /^@react-three\/stats.*/,
    /^@react-three\/text.*/,
    /^@react-three\/use-gltf.*/,
    /^@react-three\/use-helper.*/,
    /^@react-three\/use-progress.*/,
    /^@react-three\/use-spring.*/,
    /^@react-three\/use-subdivision.*/,
    /^@react-three\/use-suspense.*/,
    /^@react-three\/use-tube.*/,
    /^@react-three\/use-waggle.*/,
    /^@react-three\/use-wobble.*/,
    /^@react-three\/use-zustand.*/,
  ],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  // serverBuildPath: "build/index.js",
}; 